Persist the dynamic changes to the batch size
valory-xyz/trader pull request #156
Opened 2023-11-21 16:23 UTC by Adamantios

Closes #146.

2023-11-21 16:28 UTC, dvilelaf approved these changes

2023-11-21 16:35 UTC, 0xArdi approved these changes

2023-11-21 16:47 UTC, DavidMinarsch commented on packages/valory/skills/decision_maker_abci/behaviours/reedem.py
>                  batch_size = int(self.params.event_filtering_batch_size * keep_fraction)
It doesn't read from the right place here.

2023-11-21 16:47 UTC, DavidMinarsch commented on packages/valory/skills/decision_maker_abci/behaviours/reedem.py
>                  batch_size = int(self.params.event_filtering_batch_size * keep_fraction)
see below

2023-11-21 16:47 UTC, DavidMinarsch requested changes
Issue

2023-11-21 18:34 UTC, DavidMinarsch requested changes
Still a bug

2023-11-21 18:34 UTC, DavidMinarsch commented on packages/valory/skills/decision_maker_abci/behaviours/reedem.py
>                  keep_fraction = (1 - self.params.reduce_factor) ** n_retries
Keep fraction assumes that batch size is not incremented in the loop

2023-11-21 18:34 UTC, DavidMinarsch commented on packages/valory/skills/decision_maker_abci/behaviours/reedem.py
> +                batch_size = int(batch_size * keep_fraction)
Previously this worked because we used the non-incremented stored value. To keep this, you need to adjust keep_fraction to be constant above.

2023-11-21 18:34 UTC, DavidMinarsch commented on packages/valory/skills/decision_maker_abci/behaviours/reedem.py
> +                batch_size = int(batch_size * keep_fraction)
see above

2023-11-22 09:43 UTC, DavidMinarsch approved these changes

2023-11-22 09:43 UTC, merged