Migrate contract functionality
valory-xyz/trader pull request #218
Opened 2024-02-13 17:12 UTC by jmoreira-valory

Migrate contract functionality from market-creator to trader repository. Market creator will use the corresponding packages from trader as dependencies.

This is required to avoid a lot of code duplication when trying to implement the redeem functionalityon market creator.

2024-02-15 09:27 UTC, 0xArdi approved these changes

2024-02-15 09:33 UTC, Adamantios requested changes
LGTM, there's an unrelated issue on CI. Please skip and open an issue if you do not address it.

Did you run the agent after the changes?

2024-02-15 11:10 UTC, jmoreira-valory commented
> LGTM, there's an unrelated issue on CI. Please skip and open an issue if you do not address it.
> 
> Did you run the agent after the changes?

I didn't run the agent, but given that I am adding contract calls that are not referenced anywhere in this service, I assume there will not be any issue.

2024-02-15 14:00 UTC, Adamantios commented on packages/packages.json
> +        "skill/valory/termination_abci/0.1.0": "bafybeifdtxgldw33kwvsavcituzewwbr6iqfcsgk5qouqfhpwdrivyyyom"
??

2024-02-15 14:28 UTC, jmoreira-valory commented on packages/packages.json
> +        "skill/valory/termination_abci/0.1.0": "bafybeifdtxgldw33kwvsavcituzewwbr6iqfcsgk5qouqfhpwdrivyyyom"
fixed

```
autonomy packages sync --source valory-xyz/open-aea:v1.46.0 --update-packages
autonomy packages sync --source valory-xyz/open-autonomy:0.14.3.post1 --update-packages
```

2024-02-15 14:46 UTC, jmoreira-valory commented
Gitleaks is complaining about file `packages/valory/services/trader_omen_gnosis/service.yaml` in another branch.

2024-06-18 13:20 UTC, Adamantios approved these changes

2024-06-18 13:20 UTC, merged