[WIP]Test scripts for check_stop_trading_abci
valory-xyz/trader pull request #307
Opened 2024-08-08 13:16 UTC by Tanuj-solulab

This branch is dedicated to writing and refining test scripts for the check_stop_trading_abci function.

2024-08-09 17:04 UTC, Adamantios requested changes
The behaviours code is not covered. Please check the pytest's cov report and update accordingly:

```
Name                                                                      Stmts   Miss  Cover   Missing
-------------------------------------------------------------------------------------------------------
packages/valory/skills/check_stop_trading_abci/__init__.py                    2      0   100%
packages/valory/skills/check_stop_trading_abci/behaviours.py                 86     50    42%   60, 65, 69-77, 91-136, 147-158, 162-170
```

2024-08-09 17:04 UTC, Adamantios commented on packages/valory/skills/check_stop_trading_abci/tests/test_behaviours.py
> +        staking_kpi_met_gen = behaviour.is_staking_kpi_met()
The generator is never iterated upon.

2024-08-14 06:29 UTC, Tanuj-solulab commented on packages/valory/skills/check_stop_trading_abci/tests/test_behaviours.py
> +        staking_kpi_met_gen = behaviour.is_staking_kpi_met()
Okay i will try to improve the scripts.

2025-04-24 17:43 UTC, cyberosa commented
Added to the predict backlog for a future review of all incomplete tests for the trader.

2025-04-24 17:43 UTC, closed without merging