test for market_manager
valory-xyz/trader pull request #314
Opened 2024-08-22 05:59 UTC by Ravleen-Solulab

This PR contains test scripts for market_manager_abci.

2024-09-04 10:00 UTC, Adamantios requested changes
Please update the hashes and cover the following:
```
Name                                                                                     Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------------------------------------------------------------------------------------

packages/valory/skills/market_manager_abci/rounds.py                                        44      4    91%   57-58, 68, 85

```

Moreover, please add the `market_manager_abci` and the merged `check_stop_trading_abci` here:
https://github.com/valory-xyz/trader/blob/b04a8265ffb9f377aa2e2319884b24a923b7ed71/tox.ini#L102-L105

2024-09-04 10:22 UTC, Ravleen-Solulab commented
Could you please tell me specifically what did I miss?

2024-09-04 10:24 UTC, Adamantios commented
> Could you please tell me specifically what did I miss?

Lines 57-58, 68, 85 are not covered in rounds.

2024-09-05 09:31 UTC, Adamantios commented on packages/valory/skills/market_manager_abci/tests/test_rounds.py
> +    deserialized_data = synchronized_data._get_deserialized
This is not called, it's just assigned to `deserialized_data`.

2024-09-05 09:44 UTC, Adamantios commented on tox.ini
> +        --cov-config=.coveragerc {posargs}
```suggestion
    pytest -rfE {env:SKILLS_PATHS}/decision_maker_abci/tests --cov={env:SKILLS_PATHS}/decision_maker_abci --cov-report=xml --cov-report=term --cov-report=term-missing --cov-config=.coveragerc {posargs}
    pytest -rfE {env:SKILLS_PATHS}/check_stop_trading_abci/tests --cov={env:SKILLS_PATHS}/check_stop_trading_abci --cov-report=xml --cov-report=term --cov-report=term-missing --cov-config=.coveragerc {posargs}
    pytest -rfE {env:SKILLS_PATHS}/market_manager_abci/tests --cov={env:SKILLS_PATHS}/market_manager_abci --cov-report=xml --cov-report=term --cov-report=term-missing --cov-config=.coveragerc {posargs}
```

2024-09-05 13:46 UTC, Adamantios commented on packages/valory/skills/market_manager_abci/tests/test_rounds.py
> +from copy import deepcopy
```suggestion
```

2024-09-05 13:46 UTC, Adamantios commented on packages/valory/skills/market_manager_abci/tests/test_rounds.py
> +    payload_cls: BaseTxPayload,
```suggestion
    payload_cls: Type[BaseTxPayload],
```

2024-09-06 10:20 UTC, Adamantios approved these changes

2024-09-06 10:20 UTC, merged