Test/staking_abci
valory-xyz/trader pull request #320
Opened 2024-09-02 11:15 UTC by Ravleen-Solulab

This PR contains test scripts for staking_abci.

2024-09-06 11:39 UTC, Adamantios requested changes
Please update the command in `tox` so that the tests run on CI too.

2024-09-06 11:43 UTC, Ravleen-Solulab commented
added.

2024-09-06 11:51 UTC, Adamantios requested changes
The code is [not fully covered](https://github.com/valory-xyz/trader/actions/runs/10737747973/job/29780036508?pr=320#step:7:1043).

2024-09-09 10:09 UTC, Adamantios approved these changes

2024-09-09 10:09 UTC, merged