Test/decision_maker
valory-xyz/trader pull request #328
Opened 2024-09-19 12:51 UTC by Ravleen-Solulab

This is the PR for decision_maker_abci.
Covering : states and rounds, dialogues.

2024-10-30 11:16 UTC, Ravleen-Solulab commented
This PR contains the test script for the states(14 files), rounds and dialogues of decision_maker_abci.
Update: Everything is completed except the missing coverage in the test_redeem.py.

2024-11-08 16:52 UTC, annasambrook commented on poetry.lock
> +content-hash = "43c654a308c15072bda54f5c78ee81e355a9c7172183b4deeb3e61f2728eb6f8"
How come so many version updates to the packages here?

2024-11-08 16:54 UTC, annasambrook commented on packages/valory/skills/decision_maker_abci/tests/states/test_blacklising.py
> +        )  # Should return MOCK_TX since benchmarking is enabled
can these be parametrized?

2024-11-08 17:01 UTC, annasambrook reviewed
Left a couple of comments, otherwise LGTM

2024-11-11 10:58 UTC, annasambrook approved these changes

2024-11-13 14:39 UTC, Adamantios requested changes
There is still some uncovered code in rounds, but we can merge on `main` and continue from there.

2024-11-13 14:39 UTC, Adamantios commented on Makefile
> -	gitleaks detect --report-format json --report-path leak_report
Please revert.

2024-11-15 15:28 UTC, Adamantios approved these changes

2024-11-15 15:28 UTC, merged